export {
  AggregatedError,
  AuthenticationError,
  AuthorizationError,
  CircuitBreakerOpenError,
  ConflictError,
  DefaultErrorHandler,
  ERROR_CODES,
  ErrorCategory,
  ErrorFactory,
  InternalServerError,
  KokecoreError,
  NotFoundError,
  RateLimitExceededException,
  ServiceUnavailableError,
  ValidationError,
  categoryForCode,
  codeForStatus,
  type ErrorCode,
  type ErrorContext,
  type ErrorHandler,
  type ErrorResponse,
  type RecoverySuggestion,
} from './index';
